### ISSUE TITLE
Segmentation Fault when freeing memory at the end of simulation

### ISSUE THREAD

**Issue by xy124** [parflow/parflow#87]
It seems like freeing `PhaseRelPermFreePublicXtra` does not work properly when using the following settings in the tcl - file - can somoebody test this? :
```tcl
#----------------------------------------------------------------------------- 
# Porosity 
#----------------------------------------------------------------------------- 
 
pfset Geom.Porosity.GeomNames      "domain" 
#pfset Geom.domain.Porosity.Type        Constant 
#pfset Geom.domain.Porosity.Value       0.4 
 
pfset Geom.domain.Porosity.Type         PFBFile 
pfset Geom.domain.Porosity.FileName     porosity.pfb 
#----------------------------------------------------------------------------- 
# Relative Permeability 
#----------------------------------------------------------------------------- 
 
pfset Phase.RelPerm.Type               VanGenuchten 
pfset Phase.RelPerm.GeomNames          "domain" 
 
#pfset Geom.domain.RelPerm.Alpha            2. 
#pfset Geom.domain.RelPerm.N                2.2 
 
pfset Phase.RelPerm.VanGenuchten.File      1 
pfset Geom.domain.RelPerm.Alpha.Filename   alpha.pfb 
pfset Geom.domain.RelPerm.N.Filename       n.pfb 
#--------------------------------------------------------- 
# Saturation 
#--------------------------------------------------------- 
 
pfset Phase.Saturation.Type            VanGenuchten 
pfset Phase.Saturation.GeomNames       "domain" 
 
pfset Geom.domain.Saturation.Alpha     2. 
pfset Geom.domain.Saturation.N         2.2 
pfset Geom.domain.Saturation.SRes      0.2 
pfset Geom.domain.Saturation.SSat      0.9 
 
pfset Geom.domain.Saturation.VanGenuchten.File        1 
pfset Geom.domain.Saturation.Alpha.Filename           alpha.pfb 
pfset Geom.domain.Saturation.N.Filename               n.pfb 
pfset Geom.domain.Saturation.SRes.Filename            Sr.pfb 
pfset Geom.domain.Saturation.SSat.Filename            Ssat.pfb 
```

The log:
```
PARFLOW_DIR/bin/parflow Oueme_test                                                  
GNU gdb (GDB) bullx Linux (7.2-56.bl6.Bull.1.20121110)                           
Copyright (C) 2010 Free Software Foundation, Inc.                                      
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.            
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"            
and "show warranty" for details.                                                  
This GDB was configured as "x86_64-redhat-linux-gnu".                 
For bug reporting instructions, please see:                                  
<http://www.gnu.org/software/gdb/bugs/>...                                 
Reading symbols from /home/_/parflow_gnu/bin/parflow...done.
Starting program: /home/_/parflow_gnu/bin/parflow Oueme_test
[Thread debugging using libthread_db enabled]                        
Detaching after fork from child process 12859.   
[New Thread 0x2aaaabbe3700 (LWP 12860)]                                   
[New Thread 0x2aaaac207700 (LWP 12861)]
Node 0: Using process grid (1,1,1)
Node 0: Well Information                             
Node 0: No Wells.
Using drv_clmin.dat start time    2005.0000000000000
 CLM Start Time:         2005           1           1           0           0           0

Node 0: Well Information
Node 0: No Wells.

Program received signal SIGSEGV, Segmentation fault.
FreeSubvector (subvector=0x0) at vector.c:635
635       if (subvector->allocated)
(gdb) bt
#0  FreeSubvector (subvector=0x0) at vector.c:635
#1  0x00000000004305a4 in FreeTempVector (vector=0x9a47c0) at vector.c:652
#2  0x000000000048a599 in PhaseRelPermFreePublicXtra () at problem_phase_rel_perm.c:2067
#3  0x000000000046ba91 in FreeProblem (problem=0x977780, solver=2) at problem.c:358
#4  0x000000000041fe2f in SolverRichardsFreePublicXtra () at solver_richards.c:5633
#5  0x000000000041934c in FreeSolver () at solver.c:155
#6  0x00000000004180ff in main (argc=2, argv=0x7fffffffd338) at main.c:266
```

**Comment by kulkarni1** [comment]
bt full should show more information about variables.

**Comment by xy124** [comment]
@kulkarni1 bt full:
```
(gdb) r Oueme_test 
Starting program: /home/friedems/parflow_gnu/bin/parflow Oueme_test
[Thread debugging using libthread_db enabled]
Detaching after fork from child process 18618.
[New Thread 0x2aaaabbe3700 (LWP 18619)]
[New Thread 0x2aaaac207700 (LWP 18620)]
Node 0: Using process grid (1,1,1)
Node 0: Well Information
Node 0: No Wells.
 Using drv_clmin.dat start time    2005.0000000000000     
 CLM Start Time:         2005           1           1           0           0           0

Node 0: Well Information
Node 0: No Wells.

Program received signal SIGSEGV, Segmentation fault.
FreeSubvector (subvector=0x0) at vector.c:635
635       if (subvector->allocated)
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.5.x86_64 libgcc-4.4.6-4.bl6.x86_64 libgfortran-4.4.6-4.bl6.x86_64 libibverbs-1.1.4-1.ofed1.5.4.1.Bull.1.0.bl6.20121110.x86_64 libmlx4-1.0.1-1.ofed1.5.4.1.Bull.1.0.bl6.20121110.x86_64 libmthca-1.0.5-1.ofed1.5.4.1.Bull.1.0.bl6.20121110.x86_64 librdmacm-1.0.15-1.ofed1.5.4.1.Bull.1.0.bl6.20121110.x86_64 numactl-2.0.7-3.bl6.x86_64
(gdb) bt full
#0  FreeSubvector (subvector=0x0) at vector.c:635
No locals.
#1  0x00000000004305a4 in FreeTempVector (vector=0x9867c0) at vector.c:652
        i = <value optimized out>
#2  0x000000000048a599 in PhaseRelPermFreePublicXtra () at problem_phase_rel_perm.c:2067
        this_module = <value optimized out>
        public_xtra = 0x95e3a0
        dummy0 = <value optimized out>
        dummy1 = 0x95e700
        dummy2 = <value optimized out>
        dummy3 = <value optimized out>
        dummy4 = <value optimized out>
        num_regions = <value optimized out>
        ir = <value optimized out>
#3  0x000000000046ba91 in FreeProblem (problem=0x959780, solver=2) at problem.c:358
No locals.
#4  0x000000000041fe2f in SolverRichardsFreePublicXtra () at solver_richards.c:5633
        this_module = <value optimized out>
        public_xtra = 0x959420
#5  0x000000000041934c in FreeSolver () at solver.c:155
No locals.
#6  0x00000000004180ff in main (argc=2, argv=0x7fffffffd338) at main.c:266
        restart_read_dirname = <value optimized out>
        is_from_restart = <value optimized out>
        restore_num = <value optimized out>
        file = 0x0
        log_file = 0x0
        wall_clock_time = 7854
(gdb) 
```

**Comment by kulkarni1** [comment]
The values are optimized out. Can you recompile with O0 and run it again.

**Comment by xy124** [comment]
@kulkarni1 Which value do you need? i is zero.
Could you try if you have the same error? I fear that it is related to a malformatted alpha.pfb and n.pfb

**Comment by smithsg84** [comment]
I've been able to recreate this issue.   Developing a patch.   The vectors are being free'ed out of order with grid destruction.

**Comment by smithsg84** [comment]
The seg fault should be fixed.   Test case van-genuchten-file.tcl recreated the observed failure.

**Comment by xy124** [comment]
Thanks a lot! I tried with my example and it's fixed now!
